/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    DatePicker: typeof import('primevue/datepicker')['default']
    InputText: typeof import('primevue/inputtext')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Slider: typeof import('primevue/slider')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    Tabs: typeof import('primevue/tabs')['default']
  }
  export interface ComponentCustomProperties {
    Ripple: typeof import('primevue/ripple')['default']
  }
}
